name: nm
version: 0.0.0-dev.5

description:
  Provides a client to connect to NetworkManager - the service that manages network connections on Linux.

homepage: https://github.com/canonical/nm.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.2.1

dev_dependencies:
  pedantic: ^1.9.0
